services:

  mysql:
    image: mysql:8.0
    container_name: estapar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-simulator
    network_mode: "host"
    restart: always

  backend:
    build: .
    container_name: estapar-backend
    network_mode: "host"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: always
